#! /bin/bash
mkdir /Volumes/crunch/dutch/images/clean/sub_01
mkdir /Volumes/crunch/dutch/images/clean/sub_02
mkdir /Volumes/crunch/dutch/images/clean/sub_03
mkdir /Volumes/crunch/dutch/images/clean/sub_04
mkdir /Volumes/crunch/dutch/images/clean/sub_05
mkdir /Volumes/crunch/dutch/images/clean/sub_06
mkdir /Volumes/crunch/dutch/images/clean/sub_07
mkdir /Volumes/crunch/dutch/images/clean/sub_08
mkdir /Volumes/crunch/dutch/images/clean/sub_09
mkdir /Volumes/crunch/dutch/images/clean/sub_10
mkdir /Volumes/crunch/dutch/images/clean/sub_11
mkdir /Volumes/crunch/dutch/images/clean/sub_12
mkdir /Volumes/crunch/dutch/images/clean/sub_13
mkdir /Volumes/crunch/dutch/images/clean/sub_14
mkdir /Volumes/crunch/dutch/images/clean/sub_15
mkdir /Volumes/crunch/dutch/images/clean/sub_16
mkdir /Volumes/crunch/dutch/images/clean/sub_17
mkdir /Volumes/crunch/dutch/images/clean/sub_18
mkdir /Volumes/crunch/dutch/images/clean/sub_19
mkdir /Volumes/crunch/dutch/images/clean/sub_20
mkdir /Volumes/crunch/dutch/images/clean/sub_21
mkdir /Volumes/crunch/dutch/images/clean/sub_22
mkdir /Volumes/crunch/dutch/images/clean/sub_23
mkdir /Volumes/crunch/dutch/images/clean/sub_24
mkdir /Volumes/crunch/dutch/images/clean/sub_25
mkdir /Volumes/crunch/dutch/images/clean/sub_26
mkdir /Volumes/crunch/dutch/images/clean/sub_28
mkdir /Volumes/crunch/dutch/images/clean/sub_29
mkdir /Volumes/crunch/dutch/images/clean/sub_30
mkdir /Volumes/crunch/dutch/images/clean/sub_31
mkdir /Volumes/crunch/dutch/images/clean/sub_32
mkdir /Volumes/crunch/dutch/images/clean/sub_33
mkdir /Volumes/crunch/dutch/images/clean/sub_34
mkdir /Volumes/crunch/dutch/images/clean/sub_35
mkdir /Volumes/crunch/dutch/images/clean/sub_36
mkdir /Volumes/crunch/dutch/images/clean/sub_37
mkdir /Volumes/crunch/dutch/images/clean/sub_38
mkdir /Volumes/crunch/dutch/images/clean/sub_39
mkdir /Volumes/crunch/dutch/images/clean/sub_40
mkdir /Volumes/crunch/dutch/images/clean/sub_41
mkdir /Volumes/crunch/dutch/images/clean/sub_42
mkdir /Volumes/crunch/dutch/images/clean/sub_43
mkdir /Volumes/crunch/dutch/images/clean/sub_44
mkdir /Volumes/crunch/dutch/images/clean/sub_45
mkdir /Volumes/crunch/dutch/images/clean/sub_46
mkdir /Volumes/crunch/dutch/images/clean/sub_47
mkdir /Volumes/crunch/dutch/images/clean/sub_48
mkdir /Volumes/crunch/dutch/images/clean/sub_49
mkdir /Volumes/crunch/dutch/images/clean/sub_50