#! /bin/bash
for F in $(ls -d tps*)
do
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0001.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0002.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0003.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0004.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0005.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0006.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0007.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0008.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0009.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0010.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0011.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0012.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0013.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0014.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0015.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0016.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0017.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0018.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0019.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0020.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0021.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0022.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0023.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0024.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0025.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0026.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0027.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0028.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0029.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo1_0030.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0001.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0002.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0003.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0004.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0005.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0006.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0007.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0008.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0009.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0010.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0011.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0012.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0013.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0014.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0015.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0016.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0017.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0018.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0019.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0020.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0021.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0022.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0023.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0024.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0025.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0026.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0027.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0028.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0029.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo2_0030.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0001.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0002.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0003.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0004.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0005.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0006.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0007.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0008.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0009.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0010.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0011.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0012.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0013.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0014.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0015.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0016.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0017.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0018.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0019.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0020.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0021.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0022.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0023.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0024.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0025.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0026.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0027.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0028.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0029.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo3_0030.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0001.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0002.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0003.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0004.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0005.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0006.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0007.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0008.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0009.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0010.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0011.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0012.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0013.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0014.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0015.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0016.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0017.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0018.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0019.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0020.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0021.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0022.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0023.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0024.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0025.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0026.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0027.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0028.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0029.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo4_0030.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0001.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0002.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0003.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0004.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0005.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0006.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0007.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0008.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0009.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0010.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0011.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0012.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0013.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0014.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0015.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0016.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0017.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0018.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0019.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0020.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0021.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0022.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0023.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0024.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0025.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0026.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0027.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0028.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0029.nii /Volumes/crunch/dutch/images/clean/$F/prescan
mv /Volumes/crunch/dutch/images/clean/$F/funk/run1_echo5_0030.nii /Volumes/crunch/dutch/images/clean/$F/prescan
done