#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_NOyes.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0008.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_NOyes.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps01_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps02_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps03_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps04_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps05_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps06_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps07_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps08_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps09_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps10_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps11_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps12_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps13_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps14_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps15_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps16_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps17_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps18_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps19_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps20_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps21_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps22_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps23_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps24_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps25_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps26_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps27_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps28_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps29_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps30_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps31_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps32_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps33_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps34_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps35_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps36_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps37_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps38_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps39_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps40_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps41_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps42_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps43_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps44_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps45_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps46_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps47_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps48_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps49_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps50_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps51_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps52_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps53_NOyes.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0008.img /Volumes/crunch/dutch/betas/fx_1/tps54_NOyes.img


