#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_YESno.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0007.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_YESno.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps01_YESno.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps02_YESno.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps03_YESno.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps04_YESno.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps05_YESno.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps06_YESno.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps07_YESno.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps08_YESno.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps09_YESno.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps10_YESno.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps11_YESno.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps12_YESno.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps13_YESno.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps14_YESno.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps15_YESno.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps16_YESno.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps17_YESno.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps18_YESno.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps19_YESno.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps20_YESno.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps21_YESno.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps22_YESno.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps23_YESno.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps24_YESno.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps25_YESno.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps26_YESno.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps27_YESno.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps28_YESno.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps29_YESno.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps30_YESno.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps31_YESno.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps32_YESno.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps33_YESno.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps34_YESno.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps35_YESno.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps36_YESno.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps37_YESno.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps38_YESno.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps39_YESno.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps40_YESno.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps41_YESno.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps42_YESno.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps43_YESno.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps44_YESno.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps45_YESno.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps46_YESno.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps47_YESno.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps48_YESno.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps49_YESno.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps50_YESno.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps51_YESno.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps52_YESno.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps53_YESno.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0007.img /Volumes/crunch/dutch/betas/fx_1/tps54_YESno.img


