#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_Yes.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0003.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_Yes.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps01_Yes.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps02_Yes.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps03_Yes.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps04_Yes.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps05_Yes.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps06_Yes.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps07_Yes.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps08_Yes.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps09_Yes.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps10_Yes.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps11_Yes.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps12_Yes.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps13_Yes.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps14_Yes.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps15_Yes.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps16_Yes.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps17_Yes.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps18_Yes.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps19_Yes.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps20_Yes.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps21_Yes.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps22_Yes.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps23_Yes.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps24_Yes.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps25_Yes.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps26_Yes.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps27_Yes.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps28_Yes.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps29_Yes.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps30_Yes.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps31_Yes.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps32_Yes.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps33_Yes.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps34_Yes.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps35_Yes.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps36_Yes.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps37_Yes.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps38_Yes.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps39_Yes.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps40_Yes.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps41_Yes.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps42_Yes.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps43_Yes.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps44_Yes.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps45_Yes.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps46_Yes.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps47_Yes.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps48_Yes.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps49_Yes.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps50_Yes.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps51_Yes.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps52_Yes.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps53_Yes.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0003.img /Volumes/crunch/dutch/betas/fx_1/tps54_Yes.img


