#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_LOSEwin.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0006.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_LOSEwin.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps01_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps02_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps03_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps04_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps05_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps06_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps07_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps08_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps09_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps10_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps11_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps12_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps13_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps14_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps15_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps16_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps17_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps18_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps19_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps20_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps21_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps22_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps23_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps24_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps25_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps26_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps27_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps28_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps29_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps30_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps31_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps32_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps33_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps34_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps35_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps36_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps37_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps38_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps39_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps40_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps41_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps42_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps43_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps44_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps45_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps46_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps47_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps48_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps49_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps50_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps51_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps52_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps53_LOSEwin.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0006.img /Volumes/crunch/dutch/betas/fx_1/tps54_LOSEwin.img


