#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_WINlose.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0005.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_WINlose.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps01_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps02_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps03_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps04_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps05_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps06_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps07_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps08_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps09_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps10_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps11_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps12_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps13_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps14_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps15_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps16_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps17_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps18_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps19_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps20_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps21_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps22_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps23_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps24_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps25_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps26_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps27_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps28_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps29_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps30_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps31_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps32_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps33_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps34_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps35_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps36_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps37_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps38_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps39_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps40_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps41_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps42_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps43_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps44_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps45_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps46_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps47_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps48_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps49_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps50_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps51_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps52_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps53_WINlose.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0005.img /Volumes/crunch/dutch/betas/fx_1/tps54_WINlose.img


