#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_Win.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0001.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_Win.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps01_Win.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps02_Win.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps03_Win.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps04_Win.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps05_Win.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps06_Win.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps07_Win.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps08_Win.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps09_Win.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps10_Win.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps11_Win.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps12_Win.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps13_Win.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps14_Win.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps15_Win.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps16_Win.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps17_Win.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps18_Win.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps19_Win.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps20_Win.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps21_Win.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps22_Win.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps23_Win.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps24_Win.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps25_Win.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps26_Win.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps27_Win.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps28_Win.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps29_Win.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps30_Win.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps31_Win.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps32_Win.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps33_Win.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps34_Win.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps35_Win.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps36_Win.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps37_Win.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps38_Win.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps39_Win.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps40_Win.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps41_Win.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps42_Win.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps43_Win.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps44_Win.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps45_Win.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps46_Win.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps47_Win.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps48_Win.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps49_Win.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps50_Win.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps51_Win.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps52_Win.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps53_Win.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0001.img /Volumes/crunch/dutch/betas/fx_1/tps54_Win.img


