#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_No.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_No.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_No.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_No.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_No.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_No.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_No.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_No.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_No.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_No.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_No.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_No.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_No.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_No.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_No.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_No.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_No.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_No.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_No.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_No.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_No.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_No.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_No.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_No.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_No.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_No.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_No.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_No.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_No.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_No.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_No.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_No.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_No.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_No.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_No.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_No.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_No.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_No.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_No.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_No.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_No.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_No.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_No.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_No.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_No.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_No.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_No.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_No.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_No.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_No.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_No.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_No.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_No.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0004.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_No.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps01_No.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps02_No.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps03_No.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps04_No.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps05_No.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps06_No.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps07_No.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps08_No.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps09_No.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps10_No.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps11_No.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps12_No.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps13_No.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps14_No.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps15_No.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps16_No.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps17_No.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps18_No.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps19_No.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps20_No.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps21_No.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps22_No.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps23_No.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps24_No.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps25_No.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps26_No.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps27_No.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps28_No.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps29_No.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps30_No.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps31_No.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps32_No.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps33_No.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps34_No.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps35_No.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps36_No.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps37_No.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps38_No.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps39_No.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps40_No.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps41_No.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps42_No.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps43_No.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps44_No.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps45_No.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps46_No.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps47_No.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps48_No.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps49_No.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps50_No.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps51_No.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps52_No.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps53_No.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0004.img /Volumes/crunch/dutch/betas/fx_1/tps54_No.img


