#! /bin/bash
cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps01_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps02_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps03_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps04_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps05_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps06_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps07_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps08_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps09_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps10_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps11_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps12_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps13_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps14_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps15_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps16_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps17_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps18_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps19_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps20_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps21_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps22_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps23_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps24_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps25_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps26_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps27_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps28_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps29_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps30_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps31_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps32_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps33_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps34_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps35_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps36_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps37_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps38_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps39_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps40_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps41_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps42_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps43_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps44_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps45_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps46_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps47_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps48_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps49_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps50_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps51_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps52_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps53_Lose.hdr
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0002.hdr /Volumes/crunch/dutch/betas/fx_1/tps54_Lose.hdr

cp /Volumes/crunch/dutch/subjects/tps01/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps01_Lose.img
cp /Volumes/crunch/dutch/subjects/tps02/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps02_Lose.img
cp /Volumes/crunch/dutch/subjects/tps03/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps03_Lose.img
cp /Volumes/crunch/dutch/subjects/tps04/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps04_Lose.img
cp /Volumes/crunch/dutch/subjects/tps05/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps05_Lose.img
cp /Volumes/crunch/dutch/subjects/tps06/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps06_Lose.img
cp /Volumes/crunch/dutch/subjects/tps07/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps07_Lose.img
cp /Volumes/crunch/dutch/subjects/tps08/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps08_Lose.img
cp /Volumes/crunch/dutch/subjects/tps09/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps09_Lose.img
cp /Volumes/crunch/dutch/subjects/tps10/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps10_Lose.img
cp /Volumes/crunch/dutch/subjects/tps11/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps11_Lose.img
cp /Volumes/crunch/dutch/subjects/tps12/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps12_Lose.img
cp /Volumes/crunch/dutch/subjects/tps13/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps13_Lose.img
cp /Volumes/crunch/dutch/subjects/tps14/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps14_Lose.img
cp /Volumes/crunch/dutch/subjects/tps15/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps15_Lose.img
cp /Volumes/crunch/dutch/subjects/tps16/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps16_Lose.img
cp /Volumes/crunch/dutch/subjects/tps17/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps17_Lose.img
cp /Volumes/crunch/dutch/subjects/tps18/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps18_Lose.img
cp /Volumes/crunch/dutch/subjects/tps19/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps19_Lose.img
cp /Volumes/crunch/dutch/subjects/tps20/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps20_Lose.img
cp /Volumes/crunch/dutch/subjects/tps21/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps21_Lose.img
cp /Volumes/crunch/dutch/subjects/tps22/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps22_Lose.img
cp /Volumes/crunch/dutch/subjects/tps23/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps23_Lose.img
cp /Volumes/crunch/dutch/subjects/tps24/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps24_Lose.img
cp /Volumes/crunch/dutch/subjects/tps25/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps25_Lose.img
cp /Volumes/crunch/dutch/subjects/tps26/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps26_Lose.img
cp /Volumes/crunch/dutch/subjects/tps27/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps27_Lose.img
cp /Volumes/crunch/dutch/subjects/tps28/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps28_Lose.img
cp /Volumes/crunch/dutch/subjects/tps29/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps29_Lose.img
cp /Volumes/crunch/dutch/subjects/tps30/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps30_Lose.img
cp /Volumes/crunch/dutch/subjects/tps31/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps31_Lose.img
cp /Volumes/crunch/dutch/subjects/tps32/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps32_Lose.img
cp /Volumes/crunch/dutch/subjects/tps33/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps33_Lose.img
cp /Volumes/crunch/dutch/subjects/tps34/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps34_Lose.img
cp /Volumes/crunch/dutch/subjects/tps35/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps35_Lose.img
cp /Volumes/crunch/dutch/subjects/tps36/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps36_Lose.img
cp /Volumes/crunch/dutch/subjects/tps37/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps37_Lose.img
cp /Volumes/crunch/dutch/subjects/tps38/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps38_Lose.img
cp /Volumes/crunch/dutch/subjects/tps39/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps39_Lose.img
cp /Volumes/crunch/dutch/subjects/tps40/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps40_Lose.img
cp /Volumes/crunch/dutch/subjects/tps41/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps41_Lose.img
cp /Volumes/crunch/dutch/subjects/tps42/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps42_Lose.img
cp /Volumes/crunch/dutch/subjects/tps43/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps43_Lose.img
cp /Volumes/crunch/dutch/subjects/tps44/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps44_Lose.img
cp /Volumes/crunch/dutch/subjects/tps45/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps45_Lose.img
cp /Volumes/crunch/dutch/subjects/tps46/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps46_Lose.img
cp /Volumes/crunch/dutch/subjects/tps47/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps47_Lose.img
cp /Volumes/crunch/dutch/subjects/tps48/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps48_Lose.img
cp /Volumes/crunch/dutch/subjects/tps49/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps49_Lose.img
cp /Volumes/crunch/dutch/subjects/tps50/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps50_Lose.img
cp /Volumes/crunch/dutch/subjects/tps51/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps51_Lose.img
cp /Volumes/crunch/dutch/subjects/tps52/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps52_Lose.img
cp /Volumes/crunch/dutch/subjects/tps53/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps53_Lose.img
cp /Volumes/crunch/dutch/subjects/tps54/fx_1/con_0002.img /Volumes/crunch/dutch/betas/fx_1/tps54_Lose.img


